let paidSub={
  id: 'sub_1NkPcpGFhFwjKc9QcX2vvr4c',
  object: 'subscription',
  application: null,
  application_fee_percent: null,
  automatic_tax: { enabled: false },
  billing_cycle_anchor: 1693306703,
  billing_thresholds: null,
  cancel_at: null,
  cancel_at_period_end: false,
  canceled_at: null,
  cancellation_details: { comment: null, feedback: null, reason: null },
  collection_method: 'charge_automatically',
  created: 1693306703,
  currency: 'usd',
  current_period_end: 1695985103,
  current_period_start: 1693306703,
  customer: 'cus_OW2suOtt2f8JCo',
  days_until_due: null,
  default_payment_method: {
    id: 'pm_1NjQiRGFhFwjKc9Q6ohbDHe8',
    object: 'payment_method',
    billing_details: {
      address: [Object],
      email: 'ronwatan@gmail.com',
      name: '333',
      phone: null
    },
    card: {
      brand: 'visa',
      checks: [Object],
      country: 'US',
      exp_month: 3,
      exp_year: 2033,
      fingerprint: 'R8eQQikuT4AqkHr6',
      funding: 'credit',
      generated_from: null,
      last4: '4242',
      networks: [Object],
      three_d_secure_usage: [Object],
      wallet: null
    },
    created: 1693072567,
    customer: 'cus_OW2suOtt2f8JCo',
    livemode: false,
    metadata: {},
    type: 'card'
  },
  default_source: null,
  default_tax_rates: [],
  description: null,
  discount: null,
  ended_at: null,
  items: {
    object: 'list',
    data: [ [Object] ],
    has_more: false,
    total_count: 1,
    url: '/v1/subscription_items?subscription=sub_1NkPcpGFhFwjKc9QcX2vvr4c'
  },
  latest_invoice: 'in_1NkPcpGFhFwjKc9QJh6an5K0',
  livemode: false,
  metadata: {},
  next_pending_invoice_item_invoice: null,
  on_behalf_of: null,
  pause_collection: null,
  payment_settings: {
    payment_method_options: null,
    payment_method_types: null,
    save_default_payment_method: 'off'
  },
  pending_invoice_item_interval: null,
  pending_setup_intent: null,
  pending_update: null,
  plan: {
    id: 'price_1NiEwcGFhFwjKc9QzHvGfTpg',
    object: 'plan',
    active: true,
    aggregate_usage: null,
    amount: 999,
    amount_decimal: '999',
    billing_scheme: 'per_unit',
    created: 1692788990,
    currency: 'usd',
    interval: 'month',
    interval_count: 1,
    livemode: false,
    metadata: {},
    nickname: null,
    product: 'prod_OVFRja3rkRt0vx',
    tiers_mode: null,
    transform_usage: null,
    trial_period_days: null,
    usage_type: 'licensed'
  },
  quantity: 1,
  schedule: null,
  start_date: 1693306703,
  status: 'active',
  test_clock: null,
  transfer_data: null,
  trial_end: null,
  trial_settings: { end_behavior: { missing_payment_method: 'create_invoice' } },
  trial_start: null





}





let trailSub =
{
  id: 'sub_1NkP7GGFhFwjKc9QsATSNwtk',
  object: 'subscription',
  application: null,
  application_fee_percent: null,
  automatic_tax: { enabled: false },
  billing_cycle_anchor: 1695896746,
  billing_thresholds: null,
  cancel_at: null,
  cancel_at_period_end: false,
  canceled_at: null,
  cancellation_details: { comment: null, feedback: null, reason: null },
  collection_method: 'charge_automatically',
  created: 1693304746,
  currency: 'usd',
  current_period_end: 1695896746,
  current_period_start: 1693304746,
  customer: 'cus_OW2suOtt2f8JCo',
  days_until_due: null,







  default_payment_method: {
    id: 'pm_1NkP7EGFhFwjKc9QbpXgp1tG',
    object: 'payment_method',
    billing_details: {
      address: [Object],
      email: 'ronwatan@gmail.com',
      name: 'rtrtertert',
      phone: null
    },
    card: {
      brand: 'discover',
      checks: [Object],
      country: 'US',
      exp_month: 4,
      exp_year: 2044,
      fingerprint: 'tvQqqgWk8redp3Os',
      funding: 'credit',
      generated_from: null,
      last4: '9424',
      networks: [Object],
      three_d_secure_usage: [Object],
      wallet: null
    },
    created: 1693304744,
    customer: 'cus_OW2suOtt2f8JCo',
    livemode: false,
    metadata: {},
    type: 'card'
  },



  default_source: null,
  default_tax_rates: [],
  description: null,
  discount: null,
  ended_at: null,
  items: {
    object: 'list',
    data: [[Object]],
    has_more: false,
    total_count: 1,
    url: '/v1/subscription_items?subscription=sub_1NkP7GGFhFwjKc9QsATSNwtk'
  },
  latest_invoice: 'in_1NkP7GGFhFwjKc9QxT5ANv5x',
  livemode: false,
  metadata: {},
  next_pending_invoice_item_invoice: null,
  on_behalf_of: null,
  pause_collection: null,
  payment_settings: {
    payment_method_options: null,
    payment_method_types: null,
    save_default_payment_method: 'off'
  },
  pending_invoice_item_interval: null,
  pending_setup_intent: null,
  pending_update: null,
  plan: {
    id: 'price_1NiEwcGFhFwjKc9QzHvGfTpg',
    object: 'plan',
    active: true,
    aggregate_usage: null,
    amount: 999,
    amount_decimal: '999',
    billing_scheme: 'per_unit',
    created: 1692788990,
    currency: 'usd',
    interval: 'month',
    interval_count: 1,
    livemode: false,
    metadata: {},
    nickname: null,
    product: 'prod_OVFRja3rkRt0vx',
    tiers_mode: null,
    transform_usage: null,
    trial_period_days: null,
    usage_type: 'licensed'
  },
  quantity: 1,
  schedule: null,
  start_date: 1693304746,
  status: 'trialing',
  test_clock: null,
  transfer_data: null,
  trial_end: 1695896746,
  // current_period_end: 1695896746,
  trial_settings: { end_behavior: { missing_payment_method: 'create_invoice' } },
  trial_start: 1693304746

}


let afterCancel = {
  id: 'sub_1NkP7GGFhFwjKc9QsATSNwtk',
  object: 'subscription',
  application: null,
  application_fee_percent: null,
  automatic_tax: { enabled: false },
  billing_cycle_anchor: 1695896746,
  billing_thresholds: null,
  cancel_at: 1695896746,
  cancel_at_period_end: true,
  canceled_at: 1693304982,
  cancellation_details: { comment: null, feedback: null, reason: 'cancellation_requested' }, 
  collection_method: 'charge_automatically',
  created: 1693304746,
  currency: 'usd',
  current_period_end: 1695896746,
  current_period_start: 1693304746,
  customer: 'cus_OW2suOtt2f8JCo',
  days_until_due: null,
  default_payment_method: {
    id: 'pm_1NkP7EGFhFwjKc9QbpXgp1tG',
    object: 'payment_method',
    billing_details: {
      address: [Object],
      email: 'ronwatan@gmail.com',
      name: 'rtrtertert',
      phone: null
    },
    card: {
      brand: 'discover',
      checks: [Object],
      country: 'US',
      exp_month: 4,
      exp_year: 2044,
      fingerprint: 'tvQqqgWk8redp3Os',
      funding: 'credit',
      generated_from: null,
      last4: '9424',
      networks: [Object],
      three_d_secure_usage: [Object],
      wallet: null
    },
    created: 1693304744,
    customer: 'cus_OW2suOtt2f8JCo',
    livemode: false,
    metadata: {},
    type: 'card'
  },
  default_source: null,
  default_tax_rates: [],
  description: null,
  discount: null,
  ended_at: null,
  items: {
    object: 'list',
    data: [ [Object] ],
    has_more: false,
    total_count: 1,
    url: '/v1/subscription_items?subscription=sub_1NkP7GGFhFwjKc9QsATSNwtk'
  },
  latest_invoice: 'in_1NkP7GGFhFwjKc9QxT5ANv5x',
  livemode: false,
  metadata: {},
  next_pending_invoice_item_invoice: null,
  on_behalf_of: null,
  pause_collection: null,
  payment_settings: {
    payment_method_options: null,
    payment_method_types: null,
    save_default_payment_method: 'off'
  },
  pending_invoice_item_interval: null,
  pending_setup_intent: null,
  pending_update: null,
  plan: {
    id: 'price_1NiEwcGFhFwjKc9QzHvGfTpg',
    object: 'plan',
    active: true,
    aggregate_usage: null,
    amount: 999,
    amount_decimal: '999',
    billing_scheme: 'per_unit',
    created: 1692788990,
    currency: 'usd',
    interval: 'month',
    interval_count: 1,
    livemode: false,
    metadata: {},
    nickname: null,
    product: 'prod_OVFRja3rkRt0vx',
    tiers_mode: null,
    transform_usage: null,
    trial_period_days: null,
    usage_type: 'licensed'
  },
  quantity: 1,
  schedule: null,
  start_date: 1693304746,
  status: 'trialing',
  test_clock: null,
  transfer_data: null,
  trial_end: 1695896746,
  trial_settings: { end_behavior: { missing_payment_method: 'create_invoice' } },
  trial_start: 1693304746
}






let ddd = [
  {
    id: 'sub_1NkDKwGFhFwjKc9QfAsR8JaV',
    object: 'subscription',
    application: null,
    application_fee_percent: null,
    automatic_tax: { enabled: false },
    billing_cycle_anchor: 1695851466,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: null,
    cancellation_details: { comment: null, feedback: null, reason: null },
    collection_method: 'charge_automatically',
    created: 1693259466,
    currency: 'usd',
    current_period_end: 1695851466,
    current_period_start: 1693259466,
    customer: 'cus_OW2suOtt2f8JCo',
    days_until_due: null,
    default_payment_method: {
      id: 'pm_1NjQZVGFhFwjKc9QaTb6UZfe',
      object: 'payment_method',
      billing_details: [Object],
      card: [Object],
      created: 1693072013,
      customer: 'cus_OW2suOtt2f8JCo',
      livemode: false,
      metadata: {},
      type: 'card'
    },
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    ended_at: null,
    items: {
      object: 'list',
      data: [Array],
      has_more: false,
      total_count: 1,
      url: '/v1/subscription_items?subscription=sub_1NkDKwGFhFwjKc9QfAsR8JaV'
    },
    latest_invoice: 'in_1NkDKwGFhFwjKc9QIRoYe2Mx',
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: null,
      payment_method_types: null,
      save_default_payment_method: 'off'
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
      id: 'price_1NiEwcGFhFwjKc9QzHvGfTpg',
      object: 'plan',
      active: true,
      aggregate_usage: null,
      amount: 999,
      amount_decimal: '999',
      billing_scheme: 'per_unit',
      created: 1692788990,
      currency: 'usd',
      interval: 'month',
      interval_count: 1,
      livemode: false,
      metadata: {},
      nickname: null,
      product: 'prod_OVFRja3rkRt0vx',
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: 'licensed'
    },
    quantity: 1,
    schedule: null,
    start_date: 1693259466,
    status: 'trialing',
    test_clock: null,
    transfer_data: null,
    trial_end: 1695851466,
    trial_settings: { end_behavior: [Object] },
    trial_start: 1693259466
  },
































  {
    id: 'sub_1Nj6QTGFhFwjKc9QTcHldqPP',
    object: 'subscription',
    application: null,
    application_fee_percent: null,
    automatic_tax: { enabled: false },
    billing_cycle_anchor: 1695586572,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: 1693251936,
    cancellation_details: { comment: null, feedback: null, reason: 'cancellation_requested' },
    collection_method: 'charge_automatically',
    created: 1692994572,
    currency: 'usd',
    current_period_end: 1695586572,
    current_period_start: 1692994572,
    customer: 'cus_OW2suOtt2f8JCo',
    days_until_due: null,
    default_payment_method: null,
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    ended_at: 1693251936,
    items: {
      object: 'list',
      data: [Array],
      has_more: false,
      total_count: 1,
      url: '/v1/subscription_items?subscription=sub_1Nj6QTGFhFwjKc9QTcHldqPP'
    },
    latest_invoice: 'in_1Nj6QTGFhFwjKc9QeQH2FOEE',
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: null,
      payment_method_types: null,
      save_default_payment_method: 'off'
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
      id: 'price_1NiEwcGFhFwjKc9QzHvGfTpg',
      object: 'plan',
      active: true,
      aggregate_usage: null,
      amount: 999,
      amount_decimal: '999',
      billing_scheme: 'per_unit',
      created: 1692788990,
      currency: 'usd',
      interval: 'month',
      interval_count: 1,
      livemode: false,
      metadata: {},
      nickname: null,
      product: 'prod_OVFRja3rkRt0vx',
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: 'licensed'
    },
    quantity: 1,
    schedule: null,
    start_date: 1692994572,
    status: 'canceled',
    test_clock: null,
    transfer_data: null,
    trial_end: 1695586572,
    trial_settings: { end_behavior: [Object] },
    trial_start: 1692994572
  },
  {
    id: 'sub_1Nj6NxGFhFwjKc9Q2rwlPLEf',
    object: 'subscription',
    application: null,
    application_fee_percent: null,
    automatic_tax: { enabled: false },
    billing_cycle_anchor: 1695586417,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: 1692994446,
    cancellation_details: { comment: null, feedback: null, reason: 'cancellation_requested' },
    collection_method: 'charge_automatically',
    created: 1692994417,
    currency: 'usd',
    current_period_end: 1695586417,
    current_period_start: 1692994417,
    customer: 'cus_OW2suOtt2f8JCo',
    days_until_due: null,
    default_payment_method: {
      id: 'pm_1Nj182GFhFwjKc9QaiIXl7KT',
      object: 'payment_method',
      billing_details: [Object],
      card: [Object],
      created: 1692974210,
      customer: null,
      livemode: false,
      metadata: {},
      type: 'card'
    },
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    ended_at: 1692994446,
    items: {
      object: 'list',
      data: [Array],
      has_more: false,
      total_count: 1,
      url: '/v1/subscription_items?subscription=sub_1Nj6NxGFhFwjKc9Q2rwlPLEf'
    },
    latest_invoice: 'in_1Nj6NxGFhFwjKc9QMX58RkVN',
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: null,
      payment_method_types: null,
      save_default_payment_method: 'off'
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
      id: 'price_1NiEwcGFhFwjKc9QzHvGfTpg',
      object: 'plan',
      active: true,
      aggregate_usage: null,
      amount: 999,
      amount_decimal: '999',
      billing_scheme: 'per_unit',
      created: 1692788990,
      currency: 'usd',
      interval: 'month',
      interval_count: 1,
      livemode: false,
      metadata: {},
      nickname: null,
      product: 'prod_OVFRja3rkRt0vx',
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: 'licensed'
    },
    quantity: 1,
    schedule: null,
    start_date: 1692994417,
    status: 'canceled',
    test_clock: null,
    transfer_data: null,
    trial_end: 1695586417,
    trial_settings: { end_behavior: [Object] },
    trial_start: 1692994417
  },
  {
    id: 'sub_1Nj6MIGFhFwjKc9QNWlunawI',
    object: 'subscription',
    application: null,
    application_fee_percent: null,
    automatic_tax: { enabled: false },
    billing_cycle_anchor: 1695586314,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: 1692994349,
    cancellation_details: { comment: null, feedback: null, reason: 'cancellation_requested' },
    collection_method: 'charge_automatically',
    created: 1692994314,
    currency: 'usd',
    current_period_end: 1695586314,
    current_period_start: 1692994314,
    customer: 'cus_OW2suOtt2f8JCo',
    days_until_due: null,
    default_payment_method: {
      id: 'pm_1Nj182GFhFwjKc9QaiIXl7KT',
      object: 'payment_method',
      billing_details: [Object],
      card: [Object],
      created: 1692974210,
      customer: null,
      livemode: false,
      metadata: {},
      type: 'card'
    },
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    ended_at: 1692994349,
    items: {
      object: 'list',
      data: [Array],
      has_more: false,
      total_count: 1,
      url: '/v1/subscription_items?subscription=sub_1Nj6MIGFhFwjKc9QNWlunawI'
    },
    latest_invoice: 'in_1Nj6MIGFhFwjKc9Q9fs3eFnx',
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: null,
      payment_method_types: null,
      save_default_payment_method: 'off'
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
      id: 'price_1NiEwcGFhFwjKc9QzHvGfTpg',
      object: 'plan',
      active: true,
      aggregate_usage: null,
      amount: 999,
      amount_decimal: '999',
      billing_scheme: 'per_unit',
      created: 1692788990,
      currency: 'usd',
      interval: 'month',
      interval_count: 1,
      livemode: false,
      metadata: {},
      nickname: null,
      product: 'prod_OVFRja3rkRt0vx',
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: 'licensed'
    },
    quantity: 1,
    schedule: null,
    start_date: 1692994314,
    status: 'canceled',
    test_clock: null,
    transfer_data: null,
    trial_end: 1695586314,
    trial_settings: { end_behavior: [Object] },
    trial_start: 1692994314
  },
  {
    id: 'sub_1Nj6JRGFhFwjKc9QeC8rN6mA',
    object: 'subscription',
    application: null,
    application_fee_percent: null,
    automatic_tax: { enabled: false },
    billing_cycle_anchor: 1695586137,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: 1692994237,
    cancellation_details: { comment: null, feedback: null, reason: 'cancellation_requested' },
    collection_method: 'charge_automatically',
    created: 1692994137,
    currency: 'usd',
    current_period_end: 1695586137,
    current_period_start: 1692994137,
    customer: 'cus_OW2suOtt2f8JCo',
    days_until_due: null,
    default_payment_method: {
      id: 'pm_1Nj182GFhFwjKc9QaiIXl7KT',
      object: 'payment_method',
      billing_details: [Object],
      card: [Object],
      created: 1692974210,
      customer: null,
      livemode: false,
      metadata: {},
      type: 'card'
    },
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    ended_at: 1692994237,
    items: {
      object: 'list',
      data: [Array],
      has_more: false,
      total_count: 1,
      url: '/v1/subscription_items?subscription=sub_1Nj6JRGFhFwjKc9QeC8rN6mA'
    },
    latest_invoice: 'in_1Nj6JRGFhFwjKc9QwgVwG8l5',
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: null,
      payment_method_types: null,
      save_default_payment_method: 'off'
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
      id: 'price_1NiEwcGFhFwjKc9QzHvGfTpg',
      object: 'plan',
      active: true,
      aggregate_usage: null,
      amount: 999,
      amount_decimal: '999',
      billing_scheme: 'per_unit',
      created: 1692788990,
      currency: 'usd',
      interval: 'month',
      interval_count: 1,
      livemode: false,
      metadata: {},
      nickname: null,
      product: 'prod_OVFRja3rkRt0vx',
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: 'licensed'
    },
    quantity: 1,
    schedule: null,
    start_date: 1692994137,
    status: 'canceled',
    test_clock: null,
    transfer_data: null,
    trial_end: 1695586137,
    trial_settings: { end_behavior: [Object] },
    trial_start: 1692994137
  },
  {
    id: 'sub_1Nj6GuGFhFwjKc9QESTRTQrH',
    object: 'subscription',
    application: null,
    application_fee_percent: null,
    automatic_tax: { enabled: false },
    billing_cycle_anchor: 1695585980,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: 1692994051,
    cancellation_details: { comment: null, feedback: null, reason: 'cancellation_requested' },
    collection_method: 'charge_automatically',
    created: 1692993980,
    currency: 'usd',
    current_period_end: 1695585980,
    current_period_start: 1692993980,
    customer: 'cus_OW2suOtt2f8JCo',
    days_until_due: null,
    default_payment_method: {
      id: 'pm_1Nj182GFhFwjKc9QaiIXl7KT',
      object: 'payment_method',
      billing_details: [Object],
      card: [Object],
      created: 1692974210,
      customer: null,
      livemode: false,
      metadata: {},
      type: 'card'
    },
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    ended_at: 1692994051,
    items: {
      object: 'list',
      data: [Array],
      has_more: false,
      total_count: 1,
      url: '/v1/subscription_items?subscription=sub_1Nj6GuGFhFwjKc9QESTRTQrH'
    },
    latest_invoice: 'in_1Nj6GuGFhFwjKc9QnJjM4rE2',
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: null,
      payment_method_types: null,
      save_default_payment_method: 'off'
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
      id: 'price_1NiEwcGFhFwjKc9QzHvGfTpg',
      object: 'plan',
      active: true,
      aggregate_usage: null,
      amount: 999,
      amount_decimal: '999',
      billing_scheme: 'per_unit',
      created: 1692788990,
      currency: 'usd',
      interval: 'month',
      interval_count: 1,
      livemode: false,
      metadata: {},
      nickname: null,
      product: 'prod_OVFRja3rkRt0vx',
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: 'licensed'
    },
    quantity: 1,
    schedule: null,
    start_date: 1692993980,
    status: 'canceled',
    test_clock: null,
    transfer_data: null,
    trial_end: 1695585980,
    trial_settings: { end_behavior: [Object] },
    trial_start: 1692993980
  },
  {
    id: 'sub_1Nj6BzGFhFwjKc9QtpaxtdTN',
    object: 'subscription',
    application: null,
    application_fee_percent: null,
    automatic_tax: { enabled: false },
    billing_cycle_anchor: 1695585675,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: 1692993710,
    cancellation_details: { comment: null, feedback: null, reason: 'cancellation_requested' },
    collection_method: 'charge_automatically',
    created: 1692993675,
    currency: 'usd',
    current_period_end: 1695585675,
    current_period_start: 1692993675,
    customer: 'cus_OW2suOtt2f8JCo',
    days_until_due: null,
    default_payment_method: {
      id: 'pm_1Nj182GFhFwjKc9QaiIXl7KT',
      object: 'payment_method',
      billing_details: [Object],
      card: [Object],
      created: 1692974210,
      customer: null,
      livemode: false,
      metadata: {},
      type: 'card'
    },
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    ended_at: 1692993710,
    items: {
      object: 'list',
      data: [Array],
      has_more: false,
      total_count: 1,
      url: '/v1/subscription_items?subscription=sub_1Nj6BzGFhFwjKc9QtpaxtdTN'
    },
    latest_invoice: 'in_1Nj6BzGFhFwjKc9QhoPTgRfB',
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: null,
      payment_method_types: null,
      save_default_payment_method: 'off'
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
      id: 'price_1NiEwcGFhFwjKc9QzHvGfTpg',
      object: 'plan',
      active: true,
      aggregate_usage: null,
      amount: 999,
      amount_decimal: '999',
      billing_scheme: 'per_unit',
      created: 1692788990,
      currency: 'usd',
      interval: 'month',
      interval_count: 1,
      livemode: false,
      metadata: {},
      nickname: null,
      product: 'prod_OVFRja3rkRt0vx',
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: 'licensed'
    },
    quantity: 1,
    schedule: null,
    start_date: 1692993675,
    status: 'canceled',
    test_clock: null,
    transfer_data: null,
    trial_end: 1695585675,
    trial_settings: { end_behavior: [Object] },
    trial_start: 1692993675
  },
  {
    id: 'sub_1Nj68mGFhFwjKc9QJjxQKA1X',
    object: 'subscription',
    application: null,
    application_fee_percent: null,
    automatic_tax: { enabled: false },
    billing_cycle_anchor: 1695585475,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: 1692993598,
    cancellation_details: { comment: null, feedback: null, reason: 'cancellation_requested' },
    collection_method: 'charge_automatically',
    created: 1692993475,
    currency: 'usd',
    current_period_end: 1695585475,
    current_period_start: 1692993475,
    customer: 'cus_OW2suOtt2f8JCo',
    days_until_due: null,
    default_payment_method: {
      id: 'pm_1Nj182GFhFwjKc9QaiIXl7KT',
      object: 'payment_method',
      billing_details: [Object],
      card: [Object],
      created: 1692974210,
      customer: null,
      livemode: false,
      metadata: {},
      type: 'card'
    },
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    ended_at: 1692993598,
    items: {
      object: 'list',
      data: [Array],
      has_more: false,
      total_count: 1,
      url: '/v1/subscription_items?subscription=sub_1Nj68mGFhFwjKc9QJjxQKA1X'
    },
    latest_invoice: 'in_1Nj68mGFhFwjKc9Qw2n1Feyu',
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: null,
      payment_method_types: null,
      save_default_payment_method: 'off'
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
      id: 'price_1NiEwcGFhFwjKc9QzHvGfTpg',
      object: 'plan',
      active: true,
      aggregate_usage: null,
      amount: 999,
      amount_decimal: '999',
      billing_scheme: 'per_unit',
      created: 1692788990,
      currency: 'usd',
      interval: 'month',
      interval_count: 1,
      livemode: false,
      metadata: {},
      nickname: null,
      product: 'prod_OVFRja3rkRt0vx',
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: 'licensed'
    },
    quantity: 1,
    schedule: null,
    start_date: 1692993475,
    status: 'canceled',
    test_clock: null,
    transfer_data: null,
    trial_end: 1695585475,
    trial_settings: { end_behavior: [Object] },
    trial_start: 1692993475
  },
  {
    id: 'sub_1Nj60oGFhFwjKc9QppRjd2R5',
    object: 'subscription',
    application: null,
    application_fee_percent: null,
    automatic_tax: { enabled: false },
    billing_cycle_anchor: 1695584981,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: 1692993414,
    cancellation_details: { comment: null, feedback: null, reason: 'cancellation_requested' },
    collection_method: 'charge_automatically',
    created: 1692992981,
    currency: 'usd',
    current_period_end: 1695584981,
    current_period_start: 1692992981,
    customer: 'cus_OW2suOtt2f8JCo',
    days_until_due: null,
    default_payment_method: {
      id: 'pm_1Nj182GFhFwjKc9QaiIXl7KT',
      object: 'payment_method',
      billing_details: [Object],
      card: [Object],
      created: 1692974210,
      customer: null,
      livemode: false,
      metadata: {},
      type: 'card'
    },
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    ended_at: 1692993414,
    items: {
      object: 'list',
      data: [Array],
      has_more: false,
      total_count: 1,
      url: '/v1/subscription_items?subscription=sub_1Nj60oGFhFwjKc9QppRjd2R5'
    },
    latest_invoice: 'in_1Nj60oGFhFwjKc9Q17GZcXxX',
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: null,
      payment_method_types: null,
      save_default_payment_method: 'off'
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
      id: 'price_1NiEwcGFhFwjKc9QzHvGfTpg',
      object: 'plan',
      active: true,
      aggregate_usage: null,
      amount: 999,
      amount_decimal: '999',
      billing_scheme: 'per_unit',
      created: 1692788990,
      currency: 'usd',
      interval: 'month',
      interval_count: 1,
      livemode: false,
      metadata: {},
      nickname: null,
      product: 'prod_OVFRja3rkRt0vx',
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: 'licensed'
    },
    quantity: 1,
    schedule: null,
    start_date: 1692992981,
    status: 'canceled',
    test_clock: null,
    transfer_data: null,
    trial_end: 1695584981,
    trial_settings: { end_behavior: [Object] },
    trial_start: 1692992981
  },
  {
    id: 'sub_1Nj5yMGFhFwjKc9QtSGVcgKj',
    object: 'subscription',
    application: null,
    application_fee_percent: null,
    automatic_tax: { enabled: false },
    billing_cycle_anchor: 1695584830,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: 1692992903,
    cancellation_details: { comment: null, feedback: null, reason: 'cancellation_requested' },
    collection_method: 'charge_automatically',
    created: 1692992830,
    currency: 'usd',
    current_period_end: 1695584830,
    current_period_start: 1692992830,
    customer: 'cus_OW2suOtt2f8JCo',
    days_until_due: null,
    default_payment_method: {
      id: 'pm_1Nj182GFhFwjKc9QaiIXl7KT',
      object: 'payment_method',
      billing_details: [Object],
      card: [Object],
      created: 1692974210,
      customer: null,
      livemode: false,
      metadata: {},
      type: 'card'
    },
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    ended_at: 1692992903,
    items: {
      object: 'list',
      data: [Array],
      has_more: false,
      total_count: 1,
      url: '/v1/subscription_items?subscription=sub_1Nj5yMGFhFwjKc9QtSGVcgKj'
    },
    latest_invoice: 'in_1Nj5yMGFhFwjKc9QTaxMmVWi',
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: null,
      payment_method_types: null,
      save_default_payment_method: 'off'
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
      id: 'price_1NiEwcGFhFwjKc9QzHvGfTpg',
      object: 'plan',
      active: true,
      aggregate_usage: null,
      amount: 999,
      amount_decimal: '999',
      billing_scheme: 'per_unit',
      created: 1692788990,
      currency: 'usd',
      interval: 'month',
      interval_count: 1,
      livemode: false,
      metadata: {},
      nickname: null,
      product: 'prod_OVFRja3rkRt0vx',
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: 'licensed'
    },
    quantity: 1,
    schedule: null,
    start_date: 1692992830,
    status: 'canceled',
    test_clock: null,
    transfer_data: null,
    trial_end: 1695584830,
    trial_settings: { end_behavior: [Object] },
    trial_start: 1692992830
  }
]
