


let modelList = [{
  id: 1,
  food_name: "", description: '', remark: '', price: '',
  vetgeterian: '', vegan: '', gluten_free: '', halal: '',
  option_name_1: '', option_price_1: '',
  option_name_2: '', option_price_2: '',
  option_name_3: '', option_price_3: '',
  option_name_4: '', option_price_4: '',
  option_name_5: '', option_price_5: '',
  option_name_6: '', option_price_6: '',

},
{
  id: 2,
  food_name: '', description: '', remark: '', price: '',
  vetgeterian: '', vegan: '', gluten_free: '', halal: '',
  option_name_1: '', option_price_1: '',
  option_name_2: '', option_price_2: '',
  option_name_3: '', option_price_3: '',
  option_name_4: '', option_price_4: '',
  option_name_5: '', option_price_5: '',
  option_name_6: '', option_price_6: '',

},
{
  id: 3,
  food_name: '', description: '', remark: '', price: '',
  vetgeterian: '', vegan: '', gluten_free: '', halal: '',
  option_name_1: '', option_price_1: '',
  option_name_2: '', option_price_2: '',
  option_name_3: '', option_price_3: '',
  option_name_4: '', option_price_4: '',
  option_name_5: '', option_price_5: '',
  option_name_6: '', option_price_6: '',

},
{
  id: 4,
  food_name: '', description: '', remark: '', price: '',
  vetgeterian: '', vegan: '', gluten_free: '', halal: '',
  option_name_1: '', option_price_1: '',
  option_name_2: '', option_price_2: '',
  option_name_3: '', option_price_3: '',
  option_name_4: '', option_price_4: '',
  option_name_5: '', option_price_5: '',
  option_name_6: '', option_price_6: '',

},
{
  id: 5,
  food_name: '', description: '', remark: '', price: '',
  vetgeterian: '', vegan: '', gluten_free: '', halal: '',
  option_name_1: '', option_price_1: '',
  option_name_2: '', option_price_2: '',
  option_name_3: '', option_price_3: '',
  option_name_4: '', option_price_4: '',
  option_name_5: '', option_price_5: '',
  option_name_6: '', option_price_6: '',

},
{
  id: 6,
  food_name: '', description: '', remark: '', price: '',
  vetgeterian: '', vegan: '', gluten_free: '', halal: '',
  option_name_1: '', option_price_1: '',
  option_name_2: '', option_price_2: '',
  option_name_3: '', option_price_3: '',
  option_name_4: '', option_price_4: '',
  option_name_5: '', option_price_5: '',
  option_name_6: '', option_price_6: '',

},
{
  id: 7,
  food_name: '', description: '', remark: '', price: '',
  vetgeterian: '', vegan: '', gluten_free: '', halal: '',
  option_name_1: '', option_price_1: '',
  option_name_2: '', option_price_2: '',
  option_name_3: '', option_price_3: '',
  option_name_4: '', option_price_4: '',
  option_name_5: '', option_price_5: '',
  option_name_6: '', option_price_6: '',

},
{
  id: 8,
  food_name: '', description: '', remark: '', price: '',
  vetgeterian: '', vegan: '', gluten_free: '', halal: '',
  option_name_1: '', option_price_1: '',
  option_name_2: '', option_price_2: '',
  option_name_3: '', option_price_3: '',
  option_name_4: '', option_price_4: '',
  option_name_5: '', option_price_5: '',
  option_name_6: '', option_price_6: '',

},
{
  id: 9,
  food_name: '', description: '', remark: '', price: '',
  vetgeterian: '', vegan: '', gluten_free: '', halal: '',
  option_name_1: '', option_price_1: '',
  option_name_2: '', option_price_2: '',
  option_name_3: '', option_price_3: '',
  option_name_4: '', option_price_4: '',
  option_name_5: '', option_price_5: '',
  option_name_6: '', option_price_6: '',

},
  // {
  //   id: 10,
  //   food_name: '', description: '', remark: '', price: '',
  //   vetgeterian: '', vegan: '', gluten_free: '', halal: '',
  //   option_name_1: '', option_price_1: '',
  //   option_name_2: '', option_price_2: '',
  //   option_name_3: '', option_price_3: '',
  //   option_name_4: '', option_price_4: '',
  //   option_name_5: '', option_price_5: '',
  //   option_name_6: '', option_price_6: '',

  // },
  // {
  //   id: 11,
  //   food_name: '', description: '', remark: '', price: '',
  //   vetgeterian: '', vegan: '', gluten_free: '', halal: '',
  //   option_name_1: '', option_price_1: '',
  //   option_name_2: '', option_price_2: '',
  //   option_name_3: '', option_price_3: '',
  //   option_name_4: '', option_price_4: '',
  //   option_name_5: '', option_price_5: '',
  //   option_name_6: '', option_price_6: '',

  // },
  // {
  //   id: 12,
  //   food_name: '', description: '', remark: '', price: '',
  //   vetgeterian: '', vegan: '', gluten_free: '', halal: '',
  //   option_name_1: '', option_price_1: '',
  //   option_name_2: '', option_price_2: '',
  //   option_name_3: '', option_price_3: '',
  //   option_name_4: '', option_price_4: '',
  //   option_name_5: '', option_price_5: '',
  //   option_name_6: '', option_price_6: '',

  // },
  // {
  //   id: 13,
  //   food_name: '', description: '', remark: '', price: '',
  //   vetgeterian: '', vegan: '', gluten_free: '', halal: '',
  //   option_name_1: '', option_price_1: '',
  //   option_name_2: '', option_price_2: '',
  //   option_name_3: '', option_price_3: '',
  //   option_name_4: '', option_price_4: '',
  //   option_name_5: '', option_price_5: '',
  //   option_name_6: '', option_price_6: '',

  // },
  // {
  //   id: 14,
  //   food_name: '', description: '', remark: '', price: '',
  //   vetgeterian: '', vegan: '', gluten_free: '', halal: '',
  //   option_name_1: '', option_price_1: '',
  //   option_name_2: '', option_price_2: '',
  //   option_name_3: '', option_price_3: '',
  //   option_name_4: '', option_price_4: '',
  //   option_name_5: '', option_price_5: '',
  //   option_name_6: '', option_price_6: '',

  // },
  // {
  //   id: 15,
  //   food_name: '', description: '', remark: '', price: '',
  //   vetgeterian: '', vegan: '', gluten_free: '', halal: '',
  //   option_name_1: '', option_price_1: '',
  //   option_name_2: '', option_price_2: '',
  //   option_name_3: '', option_price_3: '',
  //   option_name_4: '', option_price_4: '',
  //   option_name_5: '', option_price_5: '',
  //   option_name_6: '', option_price_6: '',

  // },
  // {
  //   id: 16,
  //   food_name: '', description: '', remark: '', price: '',
  //   vetgeterian: '', vegan: '', gluten_free: '', halal: '',
  //   option_name_1: '', option_price_1: '',
  //   option_name_2: '', option_price_2: '',
  //   option_name_3: '', option_price_3: '',
  //   option_name_4: '', option_price_4: '',
  //   option_name_5: '', option_price_5: '',
  //   option_name_6: '', option_price_6: '',

  // },
  // {
  //   id: 17,
  //   food_name: '', description: '', remark: '', price: '',
  //   vetgeterian: '', vegan: '', gluten_free: '', halal: '',
  //   option_name_1: '', option_price_1: '',
  //   option_name_2: '', option_price_2: '',
  //   option_name_3: '', option_price_3: '',
  //   option_name_4: '', option_price_4: '',
  //   option_name_5: '', option_price_5: '',
  //   option_name_6: '', option_price_6: '',

  // },
  // {
  //   id: 18,
  //   food_name: '', description: '', remark: '', price: '',
  //   vetgeterian: '', vegan: '', gluten_free: '', halal: '',
  //   option_name_1: '', option_price_1: '',
  //   option_name_2: '', option_price_2: '',
  //   option_name_3: '', option_price_3: '',
  //   option_name_4: '', option_price_4: '',
  //   option_name_5: '', option_price_5: '',
  //   option_name_6: '', option_price_6: '',

  // },
  // {
  //   id: 19,
  //   food_name: '', description: '', remark: '', price: '',
  //   vetgeterian: '', vegan: '', gluten_free: '', halal: '',
  //   option_name_1: '', option_price_1: '',
  //   option_name_2: '', option_price_2: '',
  //   option_name_3: '', option_price_3: '',
  //   option_name_4: '', option_price_4: '',
  //   option_name_5: '', option_price_5: '',
  //   option_name_6: '', option_price_6: '',

  // },
  // {
  //   id: 20,
  //   food_name: '', description: '', remark: '', price: '',
  //   vetgeterian: '', vegan: '', gluten_free: '', halal: '',
  //   option_name_1: '', option_price_1: '',
  //   option_name_2: '', option_price_2: '',
  //   option_name_3: '', option_price_3: '',
  //   option_name_4: '', option_price_4: '',
  //   option_name_5: '', option_price_5: '',
  //   option_name_6: '', option_price_6: '',

  // },

]

export default modelList